name: base
channels:
  - conda-forge
  - rapidsai
  - defaults
  - pytorch
  - nvidia
dependencies:
  - cudatoolkit=11.7
  - cudatoolkit-dev=11.7
  - pytorch-cuda=11.7
  - pytorch
  - torchvision
  - torchaudio
  - torchdata
  - torchtext
  - pip:
    - ipywidgets
    - jupyter-lsp
    - python-language-server[all]
    - plotly
    - tqdm
    - jupyter-dash
    - modin
