name: base
channels:
  - conda-forge
  - rapidsai
  - defaults
  - pytorch
dependencies:
  - pip=22.1.1
  - cudatoolkit=11.3
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - torchdata
  - torchtext
  - pip:
    - ipywidgets>=7.6
    - jupyter-lsp
    - python-language-server[all]
    - plotly==5.8.2
    - tqdm
    - jupyter-dash
    - rapids~=22.04
