name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.1
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
    - ipywidgets>=7.6
    - jupyter-lsp
    - python-language-server[all]
    - plotly==5.8.2
    - tqdm
    - jupyter-dash
